name: inverse
description: A new Flutter project.

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Dart SDK constraint
environment:
  sdk: ">=2.17.0 <4.0.0"

# Main dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  lottie: ^3.3.1
  file: ^7.0.1


# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_lints: ^5.0.0

# Flutter launcher icons configuration
flutter_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true

# Flutter native splash configuration
flutter_native_splash:
  color: "#2b2727"
  image: assets/splash_logo.png
  android: true
  ios: true
  web: true

# Flutter assets
flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/home_screen.png
    - assets/splash_logo.png
    - assets/home_screen_b_large.png
    - assets/home_screenb.png
    - assets/background_image.png
    - assets/homescreen_rotation.png
    - assets/prem_trial.png
    - assets/success.json
    - assets/blue_success.json
    - assets/error.json
    - assets/hint.json
